### ISSUE TITLE
Create a release so pyceres can be added to conda-forge

### ISSUE THREAD

**Issue by sontung** [cvg/pyceres#12]
Hi,
Is it possible to create a release for pyceres so that it can be added to conda-forge? It will be much easier to install and manage pyceres that way.

**Comment by Skydes** [comment]
Hi, this is very much welcome! What is the process for publishing to conda-forge? Can you provide scripts to automatically build, package, and publish pyceres? [In the pycolmap repo](https://github.com/colmap/pycolmap), we automatically build pip wheels on PR update and publish to PyPI on release. You can check [how we do it](https://github.com/colmap/pycolmap/blob/master/.github/workflows/build-new.yml) and maybe adapt to conda? Thanks :)

**Comment by Skydes** [comment]
Another pointer to see how it's done for GTSAM: https://github.com/conda-forge/gtsam-feedstock

**Comment by Tobias-Fischer** [comment]
Hi @Skydes, I maintain quite a lot of robotics/vision packages on conda-forge and it would be great to see pyceres there, too. The process is quite easy, it just requires opening a pull request such as this one: https://github.com/conda-forge/staged-recipes/pull/21715

Once the pull request is approved, all build/packaging/publishing is automated in a feedstock like the gtsam once you linked above.

The first step for pyceres would be to create a release - only released packages are accepted to conda-forge. I’m happy to take care of the other steps on the conda-forge side.

**Comment by Skydes** [comment]
I've create this release: https://github.com/cvg/pyceres/releases/tag/v1.0 Thank you for offering to help, It'd be great if you could take care of the rest! Note that for the moment pyceres also requires COLMAP for its camera models.

**Comment by Tobias-Fischer** [comment]
Awesome, thanks @Skydes! Re colmap: is pyceres compatible with the 3.7 release, or does it need a newer version of colmap based off the main branch?

**Comment by Tobias-Fischer** [comment]
And one more thing - any chance to push this release to pypi?

**Comment by Skydes** [comment]
> is pyceres compatible with the 3.7 release, or does it need a newer version of colmap based off the main branch?

We require 3.8, which has now been published.

> any chance to push this release to pypi?

I'd need to setup the CI first, I'll try to get this done in the next days.

**Comment by sarlinpe** [comment]
We will setup a build CI once we've gotten rid of the dependency on COLMAP (soonish).
