### ISSUE TITLE
fatal error: colmap/base/camera_models.h: No such file or directory

### ISSUE THREAD

**Issue by joshuaoreilly** [cvg/pyceres#16]
A [recent commit](https://github.com/colmap/colmap/commit/3c38248720e62efa8adeef94b156bddf48781a72) to COLMAP moved `colmap/base/camera_models.h` to `colmap/camera/models.h`, breaking [bundle.cc](https://github.com/cvg/pyceres/blob/255198c033771e93b85ee7e1ae74ff7b3441d3d7/_pyceres/factors/bundle.cc#L1C35-L1C35). Modifying `pyceres/_pyceres/factors/bundle.cc` from

```
#include <colmap/base/camera_models.h>
```

to

```
#include <colmap/camera/models.h>
```

Allows installation to proceed.

[Full error log](https://github.com/cvg/pyceres/files/11950227/pyceres.log)

**Comment by ducha-aiki** [comment]
Ohm nice :) Now the pyceres is updated to have new colmap structure, but pixsfm not yet)
