### ISSUE TITLE
writing own costFunction

### ISSUE THREAD

**Issue by linqingfan** [cvg/pyceres#20]
Hi,
Is there a way to create own class of costFunction? I tried but it seems there is no set_num_residuals member function.
May I know if it is possible?

**Comment by Skydes** [comment]
You can create new kind of cost function by adding its C++ implementation to `_pyceres/factors/` (look at [`pose_graph.cc`](https://github.com/cvg/pyceres/blob/main/_pyceres/factors/pose_graph.cc) as an example) and binding it in [`bindings.cc`](https://github.com/cvg/pyceres/blob/main/_pyceres/factors/bindings.cc). We don't provide any way to write cost functions in Python.
