### ISSUE TITLE
Question about some pybind usage

### ISSUE THREAD

**Issue by nnop** [cvg/pyceres#21]
https://github.com/cvg/pyceres/blob/08ab2e77b96eb1f179ca9e164271eb409cf8910d/_pyceres/glog.cc#L57-L59

I saw there are many properties were bound with setters and getters. However, it seems these setters and getters were just get and set value without doing other thing. In this way, why not using `def_readwrite` or `def_readwrite_static`?

**Comment by Skydes** [comment]
You're right. Feel free to test this out and send a PR if you can. Thank you!
