### ISSUE TITLE
colmap is changed

### ISSUE THREAD

**Issue by minbre** [cvg/pyceres#24]
now colmap updated so need modification in bundle.cc

for example,
colmap/camera/models.h isn't in that directory but in colmap/sensor/models.h

because of that pyceres build error i currently can't build pixel-perfect-sfm :(

**Comment by minbre** [comment]
Thank you so much for your consideration and fast reply :) have a nice day!!

2023년 9월 20일 (수) 오전 12:07, Paul-Edouard Sarlin ***@***.***>님이
작성:

**Comment by DrAlexLiu** [comment]
I use colmap 3.8, and replace 

#include <colmap/camera/models.h>
#include <colmap/geometry/projection.h>

with 

#include <colmap/src/base/camera_models.h>
#include <colmap/src/base/projection.h>

And after changing, I can "pip install -e ." the pyceres-1.0.

**Comment by sarlinpe** [comment]
PyCeres now tracks the HEAD of COLMAP. PixSfM has not yet been updated.
