### ISSUE TITLE
Cost functions from pycolmap is not available

### ISSUE THREAD

**Issue by ShenghaoZhou** [cvg/pyceres#40]
Thanks for the nice project! I am trying to follow `examples/test_BA.ipynb`, but it seems that `cost_functions` is not `pycolmap` attribute anymore (I install pycolmap through `pip install pycolmap` directly, in a clean python 3.10 conda environment).
I tried to look around in the [pycolmap repo](https://github.com/colmap/pycolmap), and I didn't see `cost_functions` in it. I'd appreciate it if you could help me to find those pre-defined cost functions. Thanks in advance!

**Comment by sarlinpe** [comment]
As mentioned in the pycolmap README, the development has moved to [the colmap repo](https://github.com/colmap/colmap/tree/main/pycolmap). The cost functions are in [src/pycolmap/estimators/cost_functions.h](https://github.com/colmap/colmap/blob/main/src/pycolmap/estimators/cost_functions.h) but haven't made it into the previous release, so you need to build pycolmap from source rather than from PyPI. We will create a new release soon.

**Comment by ShenghaoZhou** [comment]
Thanks for the prompt response and the pointer! I was able to install pycolmap from source (from the main branch of the official colmap mentioned above). 
I still encountered an error when adding the cost function:

```python
    prob = pyceres.Problem()
    loss = pyceres.TrivialLoss()
    for im in rec.images.values():
        cam = rec.cameras[im.camera_id]
        for p in im.points2D:
---->         cost = pycolmap.cost_functions.ReprojErrorCost(
                cam.model, im.cam_from_world, p.xy
               )
``` 
 The error message is 
```
TypeError: Unable to convert function return value to a Python type! The signature was
	(camera_model_id: pycolmap.CameraModelId, cam_from_world: pycolmap.Rigid3d, point2D: numpy.ndarray[numpy.float64[2, 1]]) -> ceres::CostFunction
```
I may not install the pycolmap properly, as I copied colmap `src` folder to `pycolmap` subfolder and changed the `CMakeLists.txt` in `pycolmap` folder slightly for the path, to be able to run `python -m pip install .` successfully to install the library. 

I'd appreciate it if you could take a look into this issue.

**Comment by sarlinpe** [comment]
You likely need to install pyceres from source as well.

> I may not install the pycolmap properly, as I copied colmap src folder to pycolmap subfolder and changed the CMakeLists.txt in pycolmap folder slightly for the path, to be able to run `python -m pip install .` successfully to install the library.

Why is this needed? `python -m pip install .` should work fine when when the source files are in `src/`.

**Comment by ShenghaoZhou** [comment]
Thanks for the help. I tried to install pyceres from sources. Now there seems to be a conflict between two libraries pycolmap and pyceres. When they are imported together, the following error shows up:
```
Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
```

> Why is this needed? python -m pip install . should work fine when when the source files are in src/.
When I tried to run the command in the directory `colmap/pycolmap`, the pypi will complain it can't find source files. If I copy source files over to the same directory, it will work fine. I am not sure why. One guess is that pypi will copy things to one temporary build location, but only the current directory is included. Sorry I don't know much about how it works internally.

**Comment by sarlinpe** [comment]
> Thanks for the help. I tried to install pyceres from sources. Now there seems to be a conflict between two libraries pycolmap and pyceres. When they are imported together, the following error shows up:
Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!

Apologies for the issues. Are you building with glog < 0.6.0? These versions have an issue that has been fixed in 0.6.0. We will add a min version requirement to CMake.

> If I copy source files over to the same directory, it will work fine. I am not sure why. One guess is that pypi will copy things to one temporary build location, but only the current directory is included. Sorry I don't know much about how it works internally.

We have never experienced this in any of our build environments. What version of pip are you using?

**Comment by ShenghaoZhou** [comment]
>Apologies for the issues. Are you building with glog < 0.6.0? These versions have an issue that has been fixed in 0.6.0. We will add a min version requirement to CMake.

No worries at all, thanks for the tip! I will try again later when I have time (on the weekend most likely).

> We have never experienced this in any of our build environments. What versions of pip and Python are you using?

I am on Ubuntu 20.04, with system Python and pip via apt (Python 3.8.10, pip 20.0.2). I will try a newer version of Python and pip later.

**Comment by colin-de** [comment]
Did you solve this? After installing the pycolmap and pyceres from source I got this
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], [line 3](vscode-notebook-cell:?execution_count=4&line=3)
      [1](vscode-notebook-cell:?execution_count=4&line=1) get_ipython().run_line_magic('load_ext', 'autoreload')
      [2](vscode-notebook-cell:?execution_count=4&line=2) get_ipython().run_line_magic('autoreload', '2')
----> [3](vscode-notebook-cell:?execution_count=4&line=3) import pyceres
      [4](vscode-notebook-cell:?execution_count=4&line=4) import pycolmap
      [5](vscode-notebook-cell:?execution_count=4&line=5) import numpy as np

ImportError: libglog.so.1: cannot open shared object file: No such file or directory```

**Comment by sarlinpe** [comment]
Were pyceres and pycolmap both installed from source? This this should not occur. Did it regardless of the order in which you import them?

**Comment by ShenghaoZhou** [comment]
Sorry for the late reply. I tried to install both pyceres and pycolmap from source today (basically go to the source code folder, and run `pip install .`). I didn't encounter the problem as @colin-de (yet). But when I imported pycolmap, there is an error:
`xxx/site-packages/pycolmap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5ceres6Solver7SummaryC1Ev`

In the meantime, I can import pyceres, and run colmap itself successfully. My Ceres version from apt is 1.14.0.  I guess pycolmap might expect a different version.

**Comment by colin-de** [comment]
now it works when I install the colmap again from source after updating the glog to 0.6.0
My ceres=2.1 colmap=3.9.1

**Comment by ShenghaoZhou** [comment]
Sorry for the late reply. After building both pycolmap and pyceres from source, I am able to run the notebook without problem. For reference, I am using ceres=2.2, colmap=3.10, glog=0.6.0.
Thanks for the help and I am closing this issue.
