### ISSUE TITLE
Glog crashes when importing pyceres and pycolmap

### ISSUE THREAD

**Issue by tmnku** [cvg/pyceres#46]
I build the latest versions of pyceres (pyceres-2.2) and pycolmap (pycolmap-3.10.dev0) from source. When I import both packages I get: `F0530 14:42:58.538602 578096 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!`.

**Comment by sarlinpe** [comment]
This issue should be fixed following https://github.com/colmap/colmap/commit/e71923ebd7cf51d7417df28d7d8bf6bebf01cdf9. Did you build PyCOLMAP at HEAD? Can you confirm that your build includes this commit? Which version of glog are you using?

Also: does the issue depend on the order in which you import the packages?

**Comment by sarlinpe** [comment]
`IsGoogleLoggingInitialized` is exposed only since glog 0.6 so we can't prevent double initialization for earlier versions. AFAIK updating glog is the only solution.

**Comment by tmnku** [comment]
Thanks, I got 0.6 and everything works fine (higher versions colmap did not like).

**Comment by sarlinpe** [comment]
If you encountered issues with building COLMAP using glog 0.7.0, feel free to open an issue - this works fine on my machine but we could have missed something.
